users:list = [
    # {"name": "Tomek",
    #  "location": "Warszawa",
    #  "posts": "50",
    #  "coord": [52.23 , 21.0],
    #  "img_url": ""},
    # {"name": "Karolina",
    #  "location": "Kraśnik",
    #  "posts": "100",
    #  "img_url": ""},
    # {"name": "Jacek",
    #  "location": "Wrocław",
    #  "posts": "10",
    #  "img_url": ""},
]